services:
  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - moments_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis:/data
  web:
    image: ranjie/rmoments:v0.3.7
    restart: always
    #env_file: .env
    networks:
      - moments_network
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./data:/app/data/
networks:
  moments_network: